language: node_js

node_js:
  - 10

cache:
  directories:
    - node_modules
install: yarn

script:
  - yarn lint
  - yarn deploy

before_deploy:
  - touch .nojekyll
  - touch out/.nojekyll

deploy:
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: out
  provider: pages
  skip_cleanup: true
  target-branch: gh-pages
  on:
    branch: master