language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
install: yarn
script:
  - yarn run build
  - yarn run lint

before_deploy:
  - npm install netlify-cli -g
  - npm run deploy

deploy:
  provider: script
  script: netlify deploy -s workinfrance -t $NETLIFY_PUBLISH_KEY -p ./out
  skip_cleanup: true
  on:
    all_branches: true
