language: node_js

node_js:
  - 10

cache:
  directories:
    - node_modules
install: yarn

script:
  - yarn run lint

before_deploy:
  - yarn add netlify-cli -g
  - yarn deploy

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_PUBLISH_KEY -p --dir ./out
  skip_cleanup: true
  on:
    all_branches: true
