language: node_js

node_js:
  - 10

cache:
  directories:
    - node_modules
install: yarn

script:
  - yarn lint

before_deploy:
  - yarn global add netlify-cli
  - yarn deploy

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_PUBLISH_KEY -p --dir ./out
  skip_cleanup: true
  on:
    all_branches: true
