language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
install:
  - docker build . -t work-in-france
script:
  - docker run --name work-in-france-build work-in-france
script:
  - yarn build
  - yarn lint
after_success:
  - chmod +x ./publish.sh
  - ./publish.sh
